version: '3'
services:

    mongo_map:
        container_name: ${MONGO_CONTAINER_NAME}
        image: mongo:4.2
        network_mode: bridge
        env_file:
            - ../.env_production
        volumes:
            - ".${MONGO_DATA_DIR}:${MONGO_DATA_DIR}"
        restart: always
        ports:
            - "${MONGO_EXPOSED_PORT}:27017"
        command: "mongod"

    map_api:
        container_name: map_api
        network_mode: bridge
        links:
            - "${MONGO_CONTAINER_NAME}:${MONGO_CONTAINER_NAME}"
        build:
            context: ../
            dockerfile: api/docker/Dockerfile.production
            args:
                port: "${API_PORT}"
        env_file:
            - ../.env_production
        restart: always
        ports:
            - "${API_PORT}:${API_PORT}"
        environment:
            WAIT_HOSTS_TIMEOUT: 60
            WAIT_HOSTS: "${MONGO_CONTAINER_NAME}:27017"
